let cities = new Map([
    ["Dnipropetrovsk", 'Днепропетровск'],
    ["Moscow", "Москва"],
    ["Canberra", "Канберра"],
    ["Harare", "Хараре"],
    ["Tokio", "Токио"],
    ["Deli", "Дели"],
    ["Beijing", "Пекин"],
    ["Milan", "Милан"],
    ["Dubai", "Дубай"],
    ["Paris", "Париж"],
    ["Mumbai", "Мумбай"],
    ["Dallas", "Даллас"],
    ["Houston", "Хьюстон"],
    ["Madrid", "Мадрид"],
]);
